### PR TITLE
Added metrics: Pool points found/acknowledged last 24h

### PR DESCRIPTION
**Pull request by charnet3d**
2 New metrics added and can be used with Prometheus and Grafana: The pool points found and acknowledged in the last 24h. Calculated the same way as the Chia GUI.

### CODE REVIEW

**Review by philippnormann — CHANGES_REQUESTED** [review]
Hey @charnet3d, thanks for your PR 👍🏽 Everything looks good except that we can't change existing migrations and need to create a new one for this change. Please revert your changes to `7d540ed3aa62_add_pool_state_events_table.py` and instead make sure you that have an up to date DB with the current main branch and then create a new migration using `pipenv run alembic revision --autogenerate -m "Add points_found_24h and points_acknowledged_24h columns to pool_state_events table"`

**Comment by philippnormann** [comment]
Thinking about it a little more, I think we can already calculate these 24h changes using our existing metrics.
Could you please check if the values of your suggested calculation match the output of these PromQL queries?
```
increase(chia_pool_points_found_since_start{url="$Pool"}[24h])
``` 
```
increase(chia_pool_points_acknowledged_since_start{url="$Pool"}[24h])
```

**Comment by charnet3d** [comment]
Okey I tested your suggested PromQL query and as I expected it does not reflect the real value from the Chia client:

With the real value from the Chia clients:

image

image

image


The values with the PromQL query:

image

Both nodes have been running chia-monitor less than 24h ago so they should have a lower value in this case except that the "sam" node had to be restarted to fix an issue, so the point count was reset in the Chia client (probably a bug they should fix), something like this will make the dashboard and Chia client values not in sync.

While I prefer to report the exact value from the Chia client (the value is easily verifiable, ), it's up to you which approach we use.

**Comment by philippnormann** [comment]
Alright, the benefit of having correct values even if the monitor wasn't running for the past 24h justifies these additional metrics IMO.
As soon as you fix the migration, as I suggested in my previous comment, I will merge this into main 👍🏽

**Comment by charnet3d** [comment]
Changes committed.
Don't mind the awkward commits this is my first github PR 😄 Tried to amend the earlier commit but after the rebase the commit hash was different. And then I found somehow only one of the files was staged in the first attempt 🤦

**Review by philippnormann — APPROVED** [review]
LGTM!

**Comment by philippnormann** [comment]
Thanks for your contribution! ❤️

**Pull request merged**
